version: "3"
services:
  postgres:
    image: postgres:12.4
    hostname: localhost
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
